import type { Metadata } from "next";
import "./globals.css";

import Header from "@/components/ui/Header";
import TrpcProvider from "@/components/providers/trpc";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <TrpcProvider>{children}</TrpcProvider>
      </body>
    </html>
  );
}
